server {
    listen 80;
    listen [::]:80;
    server_name ${DOMAIN} www.${DOMAIN};

    return 301 https://${DOMAIN}$request_uri;
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name ${DOMAIN} www.${DOMAIN};

    root ${DEPLOY_PATH};
    index index.html;

    access_log /var/log/nginx/${DOMAIN}.access.log;
    error_log  /var/log/nginx/${DOMAIN}.error.log;

    ssl_certificate /etc/letsencrypt/live/${DOMAIN}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/${DOMAIN}/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    etag on;

    # brotli on;
    # brotli_comp_level 5;
    # brotli_types
    #     text/plain
    #     text/css
    #     text/javascript
    #     application/javascript
    #     application/json
    #     application/xml
    #     image/svg+xml
    #     text/html;

    gzip on;
    gzip_vary on;
    gzip_min_length 1024;
    gzip_comp_level 5;
    gzip_proxied any;
    gzip_types
        text/plain
        text/css
        text/javascript
        application/javascript
        application/json
        application/xml
        image/svg+xml;

    location ~* \.(woff2|woff|ttf|otf|eot)$ {
        add_header Cache-Control "public, max-age=0, must-revalidate";
        try_files $uri =404;
    }

	location ~* \.(css|js)$ {
        add_header Cache-Control "public, max-age=0, must-revalidate";
        try_files $uri =404;
    }

    location = /ru {
        return 301 /;
    }

    location ^~ /ru/ {
        rewrite ^/ru/(.*)$ /$1 permanent;
    }


    location / {
        try_files $uri $uri/ $uri.html =404;
    }

}
