name: Deploy blog

on:
  push:
    branches:
      - main

permissions:
  contents: read

env:
  DOMAIN: ${{ vars.DOMAIN }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install pnpm
        uses: pnpm/action-setup@v5
        with:
          cache: true

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: npm run build

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
          if_key_exists: fail

      - name: Upload files
        uses: ./.github/actions/rsync-over-ssh
        with:
          ssh_host: ${{ secrets.SSH_HOST }}
          ssh_port: ${{ secrets.SSH_PORT }}
          ssh_user: ${{ secrets.SSH_USER }}
          source_path: ./_site
          target_path: ${{ vars.DEPLOY_PATH }}

  render-nginx-config:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Render nginx config from template
        run: |
          mkdir -p ./deploy/nginx
          envsubst < ./nginx.conf > ./deploy/nginx/${DOMAIN}

      - name: Show generated config
        run: |
          cat ./deploy/nginx/${DOMAIN}

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
          if_key_exists: fail

      - name: Upload config
        uses: ./.github/actions/rsync-over-ssh
        with:
          ssh_host: ${{ secrets.SSH_HOST }}
          ssh_port: ${{ secrets.SSH_PORT }}
          ssh_user: ${{ secrets.SSH_USER }}
          source_path: ./deploy/nginx/${DOMAIN}
          target_path: /etc/nginx/sites-available/

      - name: Reload nginx
        run: |
          ssh -p "${{ secrets.SSH_PORT }}" \
            "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}" && \
             sudo nginx -t && \
             sudo systemctl reload nginx"
