name: Deploy blog

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install pnpm
        uses: pnpm/action-setup@v5
        with:
          cache: true

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: npm run build

      # - name: Install SSH Key
      #   uses: shimataro/ssh-key-action@v2
      #   with:
      #     key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
          if_key_exists: fail

      - name: Create remote directory
        uses: ./.github/actions/create-remote-dir-via-ssh
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          user: ${{ secrets.SSH_USER }}
          path: ${{ vars.DEPLOY_PATH }}

      - name: rsync over SSH
        run: rsync -r ./_site/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ vars.DEPLOY_PATH }}

      # - name: rsync deployments
      #   uses: burnett01/rsync-deployments@v8
      #   with:
      #     switches: -avzr --delete
      #     path: ./_site/
      #     remote_path: ${{ vars.DEPLOY_PATH }} # ex: /var/www/html/
      #     remote_host: ${{ secrets.SSH_HOST }} # ex: example.com
      #     remote_port: ${{ secrets.SSH_PORT }} # ex: 22
      #     remote_user: ${{ secrets.SSH_USER }} # ex: ubuntu
      #     remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
